services:
  db:
    image: postgres:16
    container_name: proximadb
    restart: unless-stopped
    environment:
      POSTGRES_DB: proximadb
      POSTGRES_USER: proxima
      POSTGRES_PASSWORD: proxima123
    ports:
      - "5433:5432"
    volumes:
      - proxima_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: proximapgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  proxima_data:
